# Generated by Django 3.0.1 on 2020-01-09 20:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 9, 20, 17, 36, 185560, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 20, 17, 36, 186559, tzinfo=utc)),
        ),
    ]
