# Generated by Django 3.0.1 on 2020-01-09 20:18

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200109_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 20, 18, 0, 823689, tzinfo=utc)),
        ),
    ]
