# Generated by Django 3.0.1 on 2020-01-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200109_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='images',
            field=models.ImageField(upload_to='pic'),
        ),
    ]
