# Generated by Django 3.0.1 on 2020-01-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200109_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='publish_date',
            field=models.DateTimeField(verbose_name=['%Y-%m-%d %H:%M:%S']),
        ),
    ]
