# Generated by Django 3.0.1 on 2020-01-10 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200110_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 19, 56, 27, 637329, tzinfo=utc)),
        ),
    ]
