# Generated by Django 3.0.1 on 2020-01-10 19:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200110_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpost',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='commentpost',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 19, 57, 14, 774506, tzinfo=utc)),
        ),
    ]
