# Generated by Django 3.0.1 on 2020-01-10 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200110_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
